### ISSUE TITLE
INVALID REQUEST

### ISSUE THREAD

**Issue by cyanideph** [deluvsushi/AminoCoinGeneratorBo#11]
>> deviceID -- 32A53FA37042DAE802EDA73BCB02DFB257740F3B969E245CA6C77096A5C7A038A253F04426174D1729
>> Invalid Request. Please update to the latest version. If the problem continues, please contact us.
>> Logged in 162a64oa@1secmail.net...
>> Lottery - Invalid Request. Please update to the latest version. If the problem continues, please contact us.
>> Watch Ad - Invalid session. Please re-login.

**Comment by deluvsushi** [comment]
update code
