### ISSUE TITLE
Register Accounts Error

### ISSUE THREAD

**Issue by DogeStanEc** [deluvsushi/AminoCoinGeneratorBo#12]
When i'm select "3" and type password for all accounts, it gives an error like this: 
"<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

list index out of range"

**Comment by deluvsushi** [comment]
Register accounts is not working now. Coz TA(Team Amino) updated web-api security.
wait update
