### ISSUE TITLE
sty не найден

### ISSUE THREAD

**Issue by DruSenpai** [deluvsushi/AminoCoinGeneratorBo#13]
![Снимок экрана (227)](https://user-images.githubusercontent.com/88430882/148032025-a8ad0b63-c19a-4b34-8c13-93c3466ca7c3.png)
![Снимок экрана (228)](https://user-images.githubusercontent.com/88430882/148032027-60be70b6-8215-4366-a4d9-2eed91048e18.png)

**Comment by deluvsushi** [comment]
Акк аниме амино 16+ лвл есть?

**Comment by DruSenpai** [comment]
> Акк аниме амино 16+ лвл есть?

только основа

**Comment by deluvsushi** [comment]
@FFuckEmWeBall напиши в телеграме
