### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ralfdep** [deluvsushi/AminoCoinGeneratorBo#16]
it is giving error to generate the 97, forbidden 403

**Comment by deluvsushi** [comment]
WHAT?

**Comment by ralfdep** [comment]
the script is giving error 403 forbidden on generation by send

**Comment by ralfdep** [comment]
after some accounts it starts showing this error 
![Uploading Screenshot_20220126-151556_Termux.jpg…]()

**Comment by ralfdep** [comment]
![Uploading Screenshot_20220126-151603_Termux.jpg…]()
