### ISSUE TITLE
tool not working

### ISSUE THREAD

**Issue by Ahmed337414** [deluvsushi/AminoCoinGeneratorBo#21]
─[root@ahmed-82c7]─[~/AminoCoinGeneratorBo]
└──╼ #python AminoCoinGeneratorBo.py 
Traceback (most recent call last):
  File "AminoCoinGeneratorBo.py", line 1, in <module>
    from pyfiglet import figlet_format
ImportError: No module named pyfiglet
┌─[✗]─[root@ahmed-82c7]─[~/AminoCoinGeneratorBo]
└──╼ #pip install  pyfiglet
Requirement already satisfied: pyfiglet in /usr/local/lib/python3.9/dist-packages (0.8.post1)
┌─[root@ahmed-82c7]─[~/AminoCoinGeneratorBo]
└──╼ #python AminoCoinGeneratorBo.py 
Traceback (most recent call last):
  File "AminoCoinGeneratorBo.py", line 1, in <module>
    from pyfiglet import figlet_format
ImportError: No module named pyfiglet
┌─[✗]─[root@ahmed-82c7]─[~/AminoCoinGeneratorBo]
└──╼ #

**Comment by deluvsushi** [comment]
wait update

**Comment by Ahmed337414** [comment]
What should I do to remove threads?
