### ISSUE TITLE
KeyError the sequel

### ISSUE THREAD

**Issue by Unusuarioc** [deluvsushi/AminoCoinGeneratorBo#24]
The script only outputs "KeyError: LinkInfoV2"  
With link input: https://aminoapps.com/c/fnaf-espanol

![Screenshot_20220514-120642466](https://user-images.githubusercontent.com/105559612/168441699-ab536c15-a468-4909-b73a-0d1fd0eb097a.jpg)

**Comment by deluvsushi** [comment]
wait update
